var Content = [
    /* Wahrheit */
    "<strong>*Wahrheit*</strong> <br/> Du befindest dich in einem Raum mit allen Personen, die du jemals getroffen hast. Nach welcher Person schaust du zuerst?",
    "<strong>*Wahrheit*</strong> <br/> Wenn du dein Leben lang nur noch einen Song hören dürftest, welcher wäre es?",
    "<strong>*Wahrheit*</strong> <br/> Wenn du dein Leben lang nur noch einen Film schauen dürftest, welcher wäre es?",
    "<strong>*Wahrheit*</strong> <br/> In welchem Alter hattest du dein erstes Mal?",
    "<strong>*Wahrheit*</strong> <br/> In welchem Alter hattest du deinen ersten Kuss?",
    "<strong>*Wahrheit*</strong> <br/> Wie hoch ist dein Bodycount?",
    "<strong>*Wahrheit*</strong> <br/> Was ist dein Guilty-Plessure?",
    "<strong>*Wahrheit*</strong> <br/> Welche:r deiner Ex-Partner:innen ist dir am meisten peinlich?",
    "<strong>*Wahrheit*</strong> <br/> Welche:r deiner Ex-Partner:innen war am besten im Bett?",
    "<strong>*Wahrheit*</strong> <br/> Welche:r deiner Ex-Partner:innen war am dümmsten?",
    "<strong>*Wahrheit*</strong> <br/> Standest du jemals auf eine:n Freund:in, ohne, dass jemand davon wusste?",
    "<strong>*Wahrheit*</strong> <br/> Aus welchem Film/Serie zitierst du am meisten?",
    "<strong>*Wahrheit*</strong> <br/> Wann warst du das letzte Mal verliebt?",
    "<strong>*Wahrheit*</strong> <br/> Wem aus der Runde schickst du die meisten Snaps?",
    "<strong>*Wahrheit*</strong> <br/> Wann hast du das letzte Mal einen Porno gesehen?",
    "<strong>*Wahrheit*</strong> <br/> Hast du jemals Nudes von dir verschickt?",
    "<strong>*Wahrheit*</strong> <br/> Hast du jemals Nudes von jemandem heimlich gespeichert/abfotografiert?",
    "<strong>*Wahrheit*</strong> <br/> Was ist das schlimmste Gerücht, das jemals über dich kursierte?",
    "<strong>*Wahrheit*</strong> <br/> Was ist das schlimmste Foto, das von dir existiert?",
    "<strong>*Wahrheit*</strong> <br/> Was war das schlimmste Date, das du jemals hattest?",
    "<strong>*Wahrheit*</strong> <br/> Was ist das Peinlichste, das dir jemals passiert ist?",
    "<strong>*Wahrheit*</strong> <br/> Worüber lügst du deine Eltern ständig an?",
    "<strong>*Wahrheit*</strong> <br/> Welchen Song magst du, obwohl du die Band/Sänger:in hasst?",
    "<strong>*Wahrheit*</strong> <br/> Wer aus dieser Runde ist deiner Meinung nach heute am schlechtesten angezogen?",
    "<strong>*Wahrheit*</strong> <br/> Hast du schon einmal Chatverläufe mit einer Person aus dieser Runde gescreenshottet und an jemand anderen weitergeschickt?",
    "<strong>*Wahrheit*</strong> <br/> Hast du Bilder von einer Person aus dieser Runde auf deinem Handy, von dem sie/er nichts weiß?",
    "<strong>*Wahrheit*</strong> <br/> Hast du aktuell einen Crush?",
    "<strong>*Wahrheit*</strong> <br/> Hast du schonmal deine:n Ex-Partner:in betrogen?",
    "<strong>*Wahrheit*</strong> <br/> Pinkelst du unter der Dusche?",
    "<strong>*Wahrheit*</strong> <br/> In wen warst du schonmal verliebt, von dem/der keine andere Person etwas wusste?",
    "<strong>*Wahrheit*</strong> <br/> Hast du schonmal deinen BH oder deine Unterhose ausgestopft?",
    "<strong>*Wahrheit*</strong> <br/> Wann hattest du deinen letzten feuchten Traum?",
    "<strong>*Wahrheit*</strong> <br/> Wann hattest du das letzte Mal Sex?",
    "<strong>*Wahrheit*</strong> <br/> Welche Beziehung bereust du am meisten?",
    "<strong>*Wahrheit*</strong> <br/> Was ist das Ungewöhnlichste, das dich anturnt?",
    "<strong>*Wahrheit*</strong> <br/> Welche drei Körperstellen findest du am anderen Geschlecht am attraktivsten?",
    "<strong>*Wahrheit*</strong> <br/> Welche drei Körperstellen findest du am gleichen Geschlecht am attraktivsten?",
    /* Pflicht */
    "<strong>*Pflicht*</strong> <br/> Verkaufe der Person gegenüber von dir einen Stift",
    "<strong>*Pflicht*</strong> <br/> Für die nächsten 5 Runden darfst du nicht den Namen deiner Mitspieler:innen benutzen - Trinke für jeden Verstoß einen Schluck",
    "<strong>*Pflicht*</strong> <br/> Tausche mit einem:r Mitspieler:in deiner Wahl das Oberteil für 3 Runden",
    "<strong>*Pflicht*</strong> <br/> Trinke einen Schluck für jede Person mit der du jemals Sex hattest",
    "<strong>*Pflicht*</strong> <br/> Für die nächsten 5 Runden darfst du nicht das Wort <i>trinken<i> und jegliche Konjugation verwenden - Trinke für jeden Verstoß einen Schluck",
    "<strong>*Pflicht*</strong> <br/> Du darfst für 1 Runde nicht den Buchstaben <i>e</i> sagen",
    "<strong>*Pflicht*</strong> <br/> Du bist Fragenmeister:in: Alle die auf deine Fragen antworten müssen einen Schluck trinken - Du waltest 2 Runden deines Amtes",
    "<strong>*Pflicht*</strong> <br/> Bringe jemanden dazu das Wort <i>Was</i> zu sagen, sonst trinke 4 Schlücke - Du hast 6 Runden Zeit.",
    "<strong>*Pflicht*</strong> <br/> Gib bei WhatsApp das Wort <i>Arsch</i> in die Suchleiste ein und lies die erste Nachricht vor.",
    "<strong>*Pflicht*</strong> <br/> Gib bei WhatsApp das Wort <i>Sex</i> in die Suchleiste ein und lies die erste Nachricht vor.",
    "<strong>*Pflicht*</strong> <br/> Zeige das 10. letzte Bild in deiner Gallerie",
    "<strong>*Pflicht*</strong> <br/> Zeige das 20. letzte Bild in deiner Gallerie",
    "<strong>*Pflicht*</strong> <br/> Trinke einen Shot Olivenöl",
    "<strong>*Pflicht*</strong> <br/> Trinke einen Shot",
    "<strong>*Pflicht*</strong> <br/> Suche dir für 3 Runden eine:n Trinkpartner:in aus - Jedes Mal wenn eine:r von euch trinken muss, trinkt der/die andere auch",
    "<strong>*Pflicht*</strong> <br/> Suche dir für 4 Runden eine:n Trinkpartner:in aus - Jedes Mal wenn eine:r von euch trinken muss, trinkt der/die andere auch",
    "<strong>*Pflicht*</strong> <br/> Suche dir für 5 Runden eine:n Trinkpartner:in aus - Jedes Mal wenn eine:r von euch trinken muss, trinkt der/die andere auch",
    "<strong>*Pflicht*</strong> <br/> Trinke für jedes Kleidungsstück, das du trägst einen Schluck (Socken = 1 Kleidungsstück)",
    "<strong>*Pflicht*</strong> <br/> Die Person rechts von dir macht dir eine Mische ihrer Wahl",
    "<strong>*Pflicht*</strong> <br/> Trink' dein Glas auf Ex",
    "<strong>*Pflicht*</strong> <br/> Verteile 2 Schlücke an eine Person deiner Wahl",
    "<strong>*Pflicht*</strong> <br/> Verteile 3 Schlücke an eine Person deiner Wahl",
    "<strong>*Pflicht*</strong> <br/> Verteile 4 Schlücke",
    "<strong>*Pflicht*</strong> <br/> Verteile 5 Schlücke",
    "<strong>*Pflicht*</strong> <br/> Führe deinen Mitspieler:innen deinen Lieblingstanzmove vor",
    "<strong>*Pflicht*</strong> <br/> Mache ein Gruppenselfie und poste es auf Instagram",
    "<strong>*Pflicht*</strong> <br/> Erzähle der Runde warum Sex mit dir ein unvergessliches Erlebnis ist.",
    "<strong>*Pflicht*</strong> <br/> Tue für 4 Runden so, als wäre eine weitere Person anwesend, die die anderen allerdings nicht sehen können",
    "<strong>*Pflicht*</strong> <br/> Gib der Person gegenüber von dir ein ernst gemeintes und ein erlogenes Kompliment - verrate aber nicht welches welches ist.",
    /* A oder B*/
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Massentierhaltung ist lit <br/> (B) Ich bin kein Nazi, ABER...",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Das mit der Digitalisierung in Deutschland ging mir entschieden zu schnell <br/> (B) Schul-Latein hat mir bisher extrem weitergeholfen",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Pornos schaue ich immer mit der Familie <br/> (B) Nestle macht generell sehr gute Arbeit",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Viva könnte mal wieder mehr von Helene Fischer spielen <br/> (B) Armut ist was für Geringverdiener:innen",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Sex mit zwei Frauen/Männern ist mir zu anstrengend <br/> (B) Anschnallen ist was für Loser",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Michael Jackson ist extrem overrated <br/> (B) Florian Silbereisen ist extrem underrated",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Gratis Globuli statt Impfung <br/> (B) Ich behaupte nicht, dass die Erde flach ist, ABER...",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Atomkraft sollte dringend weiter ausgebaut werden <br/> (B) Kurvendiskussion benutze ich oft im Alltag",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Gedichtanalyse ist extrem underrated <br/> (B) Kopfrechnen ist extrem overrated",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Zwei, drei Grad wärmer auf der Erde sind doch nicht schlimm?! <br/> (B) Bill Gates führt doch was im Schilde...",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) DSDS wird immer besser <br/> (B) Die 'Börse im Ersten' wird immer schlechter",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) An Weihnachten gibt's Formfleischpfanne <br/> (B) Brillenträger:innen simulieren doch eh nur",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Nur Heulsusen leiden an Depressionen <br/> (B) Michael Wendler macht sehr sehr gute Musik",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Der Rundfunkbeitrag ist in der Höhe absolut angemessen <br/> (B) Philipp Amthor ist sehr sehr witzig",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Sushi gehört immer erst für 10 Minuten in die Mikrowelle <br/> (B) Donald Trump würde ich wieder wählen",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) CDU/CSU-Abgeordnete sollten mehr Geld verdienen <br/> (B) Jogurtbecher gehören unausgespült ins Meer",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Ich freue mich Montags schon auf den Sat1-Fun-Freitag <br/> (B) Ich bin kein:e Coronaleugner:in, ABER...",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Die AfD ist eine echte Alternative für Deutschland <br/> (B) Jede ausgestorbene Tierart ist ein Schritt in die richtige Richtung",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Hoffentlich starb Mufasa in König der Löwen erst nach einem siebenstündigen Todeskampf <br/> (B) Mein Matheheft war zurecht immer grün",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Der Wendler hat immer recht, egal was er sagt <br/> (B) Es gibt keinen menschlich verursachten Klimawandel",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Lieber Querdenken als Queer denken <br/> (B) Ich glaube nicht an Pfand",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Die Benzinpreise dürfen gern teurer werden <br/> (B) Katholische Priester sollten grundsätzlich ein Anrecht auf Lehrerposten haben",
    "<strong>*Was stimmt eher?*</strong> <br/> (A) Wenn Mitmenschen sich nicht bedanken, nachdem man ihnen die Tür aufhält sollte man sie anspucken dürfen <br/> (B) Fast Fashion gehört in jeden Kleiderschrank",
    /* Ich habe noch nie */
    "<strong>Ich habe noch nie...</strong> <br/> mich wegen Alkohol übergeben.",
    "<strong>Ich habe noch nie...</strong> <br/> illegale Drogen genommen",
    "<strong>Ich habe noch nie...</strong> <br/> jemanden geghosted",
    "<strong>Ich habe noch nie...</strong> <br/> Sex mit dem/der Ex gehabt",
    "<strong>Ich habe noch nie...</strong> <br/> den/die Partner:in von Freund:innen ausgespannt",
    "<strong>Ich habe noch nie...</strong> <br/> einen Orgasmus vorgetäuscht",
    "<strong>Ich habe noch nie...</strong> <br/> eine schwule/lesbische Erfahrung gemacht (Küssen oder mehr)",
    "<strong>Ich habe noch nie...</strong> <br/> beim Sex an jemand anderen gedacht",
    "<strong>Ich habe noch nie...</strong> <br/> beim Sex gedacht: Wann ist es endlich vorbei",
    "<strong>Ich habe noch nie...</strong> <br/> eine Schlägerei gehabt",
    "<strong>Ich habe noch nie...</strong> <br/> bei Freund:innen gedacht, dass sie deren Partner:in nicht verdient haben",
    "<strong>Ich habe noch nie...</strong> <br/> mich in die Tasche eines Anderen übergeben.",
    "<strong>Ich habe noch nie...</strong> <br/> nach einem Suff mich von jemand anderen ins Bett bringen lassen müssen.",
    "<strong>Ich habe noch nie...</strong> <br/> mit jemandem geschlafen, den/die ich online kennengelernt habe.",
    "<strong>Ich habe noch nie...</strong> <br/> jemanden geküsst, den/die ich nicht gemocht habe.",
    "<strong>Ich habe noch nie...</strong> <br/> Freund:innen gesagt, sie sollen mit ihrem:r Partner:in Schluss machen.",
    "<strong>Ich habe noch nie...</strong> <br/> betrunken Auto gefahren.",
    "<strong>Ich habe noch nie...</strong> <br/> den/die Partner:in eines:r Freundes:in gehasst.",
    "<strong>Ich habe noch nie...</strong> <br/> mehr als zehn Bier am gleichen Abend getrunken.",
    "<strong>Ich habe noch nie...</strong> <br/> alleine getrunken.",
    "<strong>Ich habe noch nie...</strong> <br/> Analsex gehabt.",
    "<strong>Ich habe noch nie...</strong> <br/> einen One-Night-Stand gehabt.",
    "<strong>Ich habe noch nie...</strong> <br/> auf Ernst für jemanden gestrippt.",
    "<strong>Ich habe noch nie...</strong> <br/> Sex gehabt, den ich jetzt bereue.",
    "<strong>Ich habe noch nie...</strong> <br/> ein Bild verschickt, das ich besser nicht verschickt hätte.",
    "<strong>Ich habe noch nie...</strong> <br/> Sexspielzeug benutzt.",
    "<strong>Ich habe noch nie...</strong> <br/> mit zwei Personen an einem Tag geschlafen.",
    "<strong>Ich habe noch nie...</strong> <br/> mit zwei Personen an einem Abend rumgemacht.",
    "<strong>Ich habe noch nie...</strong> <br/> Sex in der Öffentlichkeit gehabt.",
    "<strong>Ich habe noch nie...</strong> <br/> für Sex bezahlt.",
    "<strong>Ich habe noch nie...</strong> <br/> nach dem Kotzen geknutscht.",
    "<strong>Ich habe noch nie...</strong> <br/> eine vergebene Person geküsst.",
    "<strong>Ich habe noch nie...</strong> <br/> 'Ich liebe dich' gesagt, obwohl es nicht stimmte.",
    "<strong>Ich habe noch nie...</strong> <br/> gekifft.",
    "<strong>Ich habe noch nie...</strong> <br/> mir gewünscht, dass mein Penis/meine Brüste größer wären.",
    "<strong>Ich habe noch nie...</strong> <br/> einen offene Beziehung gehabt.",
    "<strong>Ich habe noch nie...</strong> <br/> einen Stripclub besucht.",
    "<strong>Ich habe noch nie...</strong> <br/> mich beim Sex gefilmt.",
    "<strong>Ich habe noch nie...</strong> <br/> Sex geahbt, während ein Haustier anwesend war.",
    "<strong>Ich habe noch nie...</strong> <br/> per Textnachricht Schluss gemacht.",
    "<strong>Ich habe noch nie...</strong> <br/> bei 'Ich habe noch nie' gelogen.",
    "<strong>Ich habe noch nie...</strong> <br/> gelacht, wenn jemand hingefallen ist.",
    "<strong>Ich habe noch nie...</strong> <br/> meine Sorgen weggetrunken.",
    "<strong>Ich habe noch nie...</strong> <br/> alleine abends in einem Restaurant gegessen.",
    "<strong>Ich habe noch nie...</strong> <br/> mit einer Person geschlafen, der/die mehr als zehn Jahre älter war als ich.",
    "<strong>Ich habe noch nie...</strong> <br/> in der Schule rumgemacht.",
    "<strong>Ich habe noch nie...</strong> <br/> einen Filmriss gehabt.",
    "<strong>Ich habe noch nie...</strong> <br/> meine:n Partner:in ausversehen beim falschen Namen gerufen.",
    /* Kategorie */
    "<strong>*Kategorie*</strong> <br/> Länder Europas",
    "<strong>*Kategorie*</strong> <br/> Hauptstädte Europas",
    "<strong>*Kategorie*</strong> <br/> Bundesstaaten in den USA",
    "<strong>*Kategorie*</strong> <br/> Automarken",
    "<strong>*Kategorie*</strong> <br/> Flüsse Deutschlands",
    "<strong>*Kategorie*</strong> <br/> Sprachen",
    "<strong>*Kategorie*</strong> <br/> Länder Asiens",
    "<strong>*Kategorie*</strong> <br/> Länder Afrikas",
    "<strong>*Kategorie*</strong> <br/> Anglizismen",
    "<strong>*Kategorie*</strong> <br/> Musikgenre",
    "<strong>*Kategorie*</strong> <br/> Olympische Sportarten (Sommer)",
    "<strong>*Kategorie*</strong> <br/> Olympische Sportarten (Winter)",
    "<strong>*Kategorie*</strong> <br/> Ballsportarten",
    "<strong>*Kategorie*</strong> <br/> Vornamen mit <i>C</i>",
    "<strong>*Kategorie*</strong> <br/> Vornamen mit <i>I</i>",
    "<strong>*Kategorie*</strong> <br/> Vornamen mit <i>U</i>",
    "<strong>*Kategorie*</strong> <br/> Fastfoodketten",
    "<strong>*Kategorie*</strong> <br/> Gemüse",
    "<strong>*Kategorie*</strong> <br/> Obst",
    "<strong>*Kategorie*</strong> <br/> Englischsprachige Länder",
    "<strong>*Kategorie*</strong> <br/> Chemische Elemente des Periodensystems",
    "<strong>*Kategorie*</strong> <br/> Charaktere aus Harry Potter",
    "<strong>*Kategorie*</strong> <br/> Pokémon",
    "<strong>*Kategorie*</strong> <br/> Vögel",
    "<strong>*Kategorie*</strong> <br/> Raubkatzen",
    "<strong>*Kategorie*</strong> <br/> Dinosaurier",
    "<strong>*Kategorie*</strong> <br/> Ausgestorbene Tierarten (Keine Dinosaurier)",
    "<strong>*Kategorie*</strong> <br/> Hunderassen (Keine Mischlinge)",
    "<strong>*Kategorie*</strong> <br/> Bierbrauereien",
    "<strong>*Kategorie*</strong> <br/> Laubbäume",
    "<strong>*Kategorie*</strong> <br/> Kleidungsstücke",
    "<strong>*Kategorie*</strong> <br/> Gewürze",
    "<strong>*Kategorie*</strong> <br/> Bundeskanzler:innen Deutschlands",
    
    /* Entweder - Oder */
    "<strong>*Stimmt ab*</strong> <br/> Barfuß oder Socken?",
    "<strong>*Stimmt ab*</strong> <br/> Playstation oder X-Box?",
    "<strong>*Stimmt ab*</strong> <br/> Kika oder Nickelodeon?",
    "<strong>*Stimmt ab*</strong> <br/> Mercedes oder BMW?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber hässlich und beliebt oder schön und unbeliebt?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber dumm und berühmt oder intelligent und nicht berühmt?",
    "<strong>*Stimmt ab*</strong> <br/> Samstag oder Sonntag?",
    "<strong>*Stimmt ab*</strong> <br/> Die oder Das Nutella?",
    "<strong>*Stimmt ab*</strong> <br/> Singleleben oder Beziehung?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber am Fenster oder am Gang sitzen?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber Torwart:in oder Feldspieler:in?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber Regisseur:in oder Schauspieler:in?",
    "<strong>*Stimmt ab*</strong> <br/> Lieber 1,40m oder 2,30m sein?",
    "<strong>*Stimmt ab*</strong> <br/> Android oder iPhone?",
    "<strong>*Stimmt ab*</strong> <br/> Stadt oder Dorf?",
    "<strong>*Stimmt ab*</strong> <br/> McDonalds oder Burger King?",
    "<strong>*Stimmt ab*</strong> <br/> Hund oder Katze?",
    "<strong>*Stimmt ab*</strong> <br/> Cola oder Pepsi?",
    "<strong>*Stimmt ab*</strong> <br/> Winter oder Sommer?",
    "<strong>*Stimmt ab*</strong> <br/> Herbst oder Frühling?",
    "<strong>*Stimmt ab*</strong> <br/> Mathe oder Englisch?",
    "<strong>*Stimmt ab*</strong> <br/> Strandurlaub oder Städtetrip?",
    "<strong>*Stimmt ab*</strong> <br/> Frühstück oder Abendessen?",
    "<strong>*Stimmt ab*</strong> <br/> Süßes oder salziges Popcorn?",
    "<strong>*Stimmt ab*</strong> <br/> Süßkartoffelpommes oder Salzige?",
    "<strong>*Stimmt ab*</strong> <br/> Bier oder Wein?",
    "<strong>*Stimmt ab*</strong> <br/> Singen oder Tanzen?",
    "<strong>*Stimmt ab*</strong> <br/> Charakter oder Aussehen?",
    "<strong>*Stimmt ab*</strong> <br/> Intelligenz oder Humor?",
    "<strong>*Stimmt ab*</strong> <br/> Jünger oder Älter?",
    "<strong>*Stimmt ab*</strong> <br/> Herz oder Kopf?",
    "<strong>*Stimmt ab*</strong> <br/> Nie wieder Musik hören, oder immer den gleichen Song?",
    "<strong>*Stimmt ab*</strong> <br/> Deine Eltern beim Sex erwischen, oder von deinen Eltern dabei erwischt werden?",
    "<strong>*Stimmt ab*</strong> <br/> Morgenmuffel oder Morgenmensch?",
    "<strong>*Stimmt ab*</strong> <br/> Telefonieren oder Schreiben?",
    "<strong>*Stimmt ab*</strong> <br/> Oben oder Unten?",
    "<strong>*Stimmt ab*</strong> <br/> Fesseln oder Augenbinde?",
    "<strong>*Stimmt ab*</strong> <br/> Fesseln oder gefesselt werden?",
    "<strong>*Stimmt ab*</strong> <br/> Nutella mit oder ohne Butter?",
    "<strong>*Stimmt ab*</strong> <br/> Zuerst Milch oder zuerst Müsli?",
    /* Wer würde eher */
    "<strong>Wer würde eher...</strong> <br/> ins Ausland ziehen?",
    "<strong>Wer würde eher...</strong> <br/> bei einem Brettspiel die Selbstbeherrschung komplett verlieren?",
    "<strong>Wer würde eher...</strong> <br/> bei einer Feier mit einer fremden Person rummachen?",
    "<strong>Wer würde eher...</strong> <br/> nach einer Feier mit einer fremden Person nach Hause gehen?",
    "<strong>Wer würde eher...</strong> <br/> als erstes verheiratet sein?",
    "<strong>Wer würde eher...</strong> <br/> gefeuert werden?",
    "<strong>Wer würde eher...</strong> <br/> privatinsolvent werden?",
    "<strong>Wer würde eher...</strong> <br/> fremdgehen?",
    "<strong>Wer würde eher...</strong> <br/> ein Kind schubsen?",
    "<strong>Wer würde eher...</strong> <br/> zweimal die selbe Unterhose tragen?",
    "<strong>Wer würde eher...</strong> <br/> in die Dusche pinkeln?",
    "<strong>Wer würde eher...</strong> <br/> Wurstwasser für Geld trinken?",
    "<strong>Wer würde eher...</strong> <br/> einen Dreier haben?",
    "<strong>Wer würde eher...</strong> <br/> an einer Orgie teilnehmen?",
    "<strong>Wer würde eher...</strong> <br/> im Urlaub seine:n Partner:in betrügen?",
    "<strong>Wer würde eher...</strong> <br/> einen Swingerclub besuchen?",
    "<strong>Wer würde eher...</strong> <br/> BDSM ausprobieren?",
    "<strong>Wer würde eher...</strong> <br/> mit jemandem schlafen, den er/sie nicht mag?",
    "<strong>Wer würde eher...</strong> <br/> eine Sexschaukel ausprobieren?",
    "<strong>Wer würde eher...</strong> <br/> einen Porno drehen?",
    "<strong>Wer würde eher...</strong> <br/> einen Fußfetisch haben?",
    "<strong>Wer würde eher...</strong> <br/> nackt für Geld putzen?",
    "<strong>Wer würde eher...</strong> <br/> jetzt nackt durch die Stadt rennen?",
    "<strong>Wer würde eher...</strong> <br/> eine kriminelle Laufbahn einschlagen?",
    "<strong>Wer würde eher...</strong> <br/> alleine in der Wildnis überleben?",
    "<strong>Wer würde eher...</strong> <br/> 1 Liter Bier auf Ex trinken?",
    "<strong>Wer würde eher...</strong> <br/> am schnellsten ein Bier wegtrichtern?",
    "<strong>Wer würde eher...</strong> <br/> sich besoffen ein Tattoo stechen lassen?",
    "<strong>Wer würde eher...</strong> <br/> früher oder später im Trash-TV zu sehen sein?",
    /* Strafe */
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
    "<strong>*Strafrunde*</strong> <br/> Alle trinken einen Schluck!",
]

// Create Function to Randomize Content
function new_content() {
    var randomContent = Math.floor(Math.random() * (Content.length));
    document.getElementById("content").innerHTML = Content[randomContent];
    Content.splice(randomContent, 1);
}

/* function openRules() {
    rules = [
        " (💬) WAHRHEIT: Antworte oder trinke",
        " (🎭) WAS STIMMT EHER: Alle stimmen ab - Die Minderheit trinkt",
        " ❌ Disclaimer: Diese Fragen sind sarkastisch/satirisch gemeint",
        " (👍🏽) STIMMT AB: Alle stimmen ab - Die Minderheit trinkt",
        " (🤡) ICH HABE NOCH NIE: Wie gewohnt",
        " (🤔) WER WÜRDE EHER: Alle stimmen ab - Spieler:in mit den meisten Stimmen trinkt",
        " (📒) KATEGORIE: Alle zählen im Uhrzeigersinn Dinge zur gegebenen Kategorie auf - Verlierer:in trinkt"
]

            window.alert("REGELN: " + rules)
}

function openHelp() {
    window.alert("Hey! 🤗 Ich bin IT-Student. Da die meisten solcher Apps kostenpflichtig sind, ist diese Website for free! Möchtest du mich dennoch unterstützen, kannst du mir gerne eine kleines Trinkgeld per PayPal dalassen 🙏🏽 Vielen Dank und Viel Spaß! 👻")
} */