var Content = [
    /* Season 1 */
    "Was ist Etwas, das für dich niemals unlustig wird <br/>- so oft du es auch hörst/siehst?",
    "Was ist Etwas, das für dich niemals an Faszination verliert <br/>-so oft du es auch hörst/siehst?",
    "Was ist Etwas, das für dich niemals an Bedeutung verliert?",
    "In welchen Situationen bist du unverhältnismäßig patriotisch?",
    "Wenn du dich für jede Person auf der Welt entscheiden könntest: <br/>Wen würdest du als Gast zu dir nach Haus einladen?",
    "Wärst du gerne berühmt?",
    "Wie wärst du so als Promi?",
    "Hast du jemals geprobt was du sagen willst, bevor du eine Sprachnachricht verfasst hast? <br/>- Wenn ja, weshalb?",
    "Wie würde dein perfekter Tag aussehen?",
    "Du bist 90 Jahre alt. Du könntest entweder den Geist oder den Körper deines 30-jährigen Ich behalten. <br/>Wie entscheidest du dich?",
    "Hattest du schon einmal eine Vorahnung, wie du mal sterben wirst?",
    "3 Dinge, die du und ich gemeinsam haben?",
    "Für was bist du in deinem bisherigen Leben am dankbarsten?",
    "Wenn du auf deine Erziehung zurückblickst und du heute etwas ändern könntest, was wäre das?",
    "Stell dir vor du würdest morgen mit irgendeiner neuen Eigenschaft oder Fähigkeit aufwachen - <br/>Welche hättest du gerne?",
    "Du sitzt deinem 90-Jährigen Ich gegenüber - Was würdest du als erstes fragen?",
    "Was wolltest du schon immer gerne machen, das du noch nie getan hast?",
    "Was ist dein bisher größter Erfolg?",
    "Was ist für dich in einer Freundschaft das Wichtigste?",
    "Wenn du dir die schönsten Momente deines Lebens vorstellst - <br/>Welcher Moment ist am präsentesten?",
    "Wenn du dir die schönsten Momente deines Lebens vorstellst - <br/>Welcher Moment ist am präsentesten?",
    "Was für eine Bedeutung hat Freundschaft in deinem Leben?",
    "Welche Rolle spielen Liebe und Zuneigung in deinem Leben?",
    "Sagt euch abwechselnd, welche positiven Charakterzüge euer Gegenüber hat <br/>-Jede:r soll dabei 3 nennen.",
    "Hast du das Gefühl, dass deine Kindheit glücklicher war als die der Meisten?",
    "Wie ist die Beziehung zwischen dir und deiner Mutter?",
    "Wie ist die Beziehung zwischen dir und deinem Vater?",
    "Vervollständige folgenden Satz: <br/>'Ich wünschte ich hätte jemanden, mit dem ich [...] teilen könnte.'",
    "Wenn du mit deinem Gegenüber eng befreundet sein wolltest <br/>- Was wäre dann für ihn/sie wichtig zu wissen?",
    "Sage deinem Gegenüber, was du an ihm/ihr magst <br/>- Allerdings nur Dinge, die du einer Person, die du zum ersten Mal triffst, vielleicht nicht direkt sagen würdest.",
    "Wenn du dir die peinlichsten Momente deines Lebens vorstellst <br/>- Welcher Moment ist am präsentesten?",
    "Wann hast du das letzte Mal vor einer anderen Person geweint?",
    "Wann hast du das letzte Mal geweint?",
    "Etwas, das du bereits nach 5 Minuten wusstest, an deinem Gegenüber zu mögen?",
    "Worüber sollte man keine Witze machen?",
    "Wenn du heute Abend sterben würdest, ohne mit jemandem gesprochen zu haben <br/>- Was würdest du bereuen nicht mehr gesagt zu haben? <br/>Warum hast du es bisher nicht gesagt?",
    "Dein Haus, mit allem was dir gehört fängt Feuer <br/>-Nachdem du deine Liebsten gerettet hast bleibt dir noch Zeit um genau einen Gegenstand zu sichern. <br/>Welcher wäre das?",
    "Wie wichtig ist es dir, dass dich andere Personen mögen?",
    "Welches Wort sagt du zu häufig?",
    "Sing Menschen von Natur aus gut/schlecht?",

    /* Season 2 */
    "Welche Farbe dominiert deinen Kleiderschrank?",
    "Wenn du vom anderen Geschlecht wärst: Auf welchen Typ Mann/Frau würdest du dann stehen?",
    "Wer war dein 'Childhoodcrush'?",
    "Wer ist dein aktueller 'Celebritycrush'?",
    "Hast du jemals gegen ein Gesetz verstoßen?",
    "Wofür hast du eine 'secret Obsession'?",
    "Was ist dein 'guilty Plessure'?",
    "Was glaubst du, schätzen deine Freund:innen am Meisten an dir?",
    "Was glaubst du, mögen deine Freund:innen nicht an dir?",
    "Losgelöst von allen Aspekten <br/>- Was würdest du am liebsten studieren?",
    "Was ist dein 'Comfortmovie'?",
    "Welcher Song ist dein 'Evergreen'?",
    "Was ist ein Nieschenbereich, in dem du dich erstaunlich gut auskennst?",
    "Körperlich betrachtet <br/>- Wann warst du in der 'Form deines Lebens'?",
    "In welchem Bereich agierst du oft zu naiv?",
    "In welchen Situationen agiert du oft zu verbissen?",
    "Was ist deine 'Schokoladenseite'?",
    "Was ist DEIN Thema?",
    "In welchem Bereich würdest du dich gerne besser auskennen?",
    "Welcher Mensch in deinem Leben hat dich charakterlich positiv überrascht, als du ihn/sie besser kennengelernt hast?",
    "Wer kennt dich am Besten?",
    "Abgesehen von deiner Familie <br/>- Wer kennt dich am Besten?",
    "Mit welchen deiner Freund:innen sprichst du am liebsten über deine Gefühlswelt?",
    "Welches Thema trifft bei dir auf einen besonders sensiblen Nerv?",
    "Was ist dein größter Trigger?",
    "Hast du schon einmal eine andere Person deines Geschlechts geküsst?",
    "Was ist eine Sache, von der du als Kind fälschlicherweise dachtest, <br/>dass es in deinem späteren Leben einmal eine Rolle spielen würde?",
    "Welches ist dein liebstes Bild von dir?",
    "Mit welcher Eigenschaft würde man dich deiner Meinung nach als erstes beschreiben, <br/>wenn eine Person mit deinem Namen nichts anfangen kann? <br/>- Z.B.: 'Der mit der zu großen Brille.'",
    "Ohne welche App könntest du aktuell nicht auskommen?",
    "Wie hoch ist dein 'Bodycount'?",
    "Wofür lässt du dir laut anderen ungewöhnlich lange Zeit?",
    "In welchem Alter hattest du dein erstes Mal?",
    "In welchem Alter hattest du deinen ersten Kuss?",
    "Dein erster Kuss: <br/>War gut oder eher nicht?",
    "Du befindest dich in einem Raum mit allen Personen, die du jemals getroffen hast <br/>- Nach wem siehst du zuerst?",
    "Hast du jemals 'Nudes' von dir verschickt?",
    "Welche von deinen bisherigen Beziehungen bereust du am meisten?",
    "Was ist das Ungewöhnlichste, das dich anturnt?",
    "3 Körperstellen, die du an deinem Gegenüber am Attraktivsten findest?",

    /* Season 3 */
    "Hast du schon einmal jemanden geliebt?",
    "In welchem Bereich/um welche Fähigkeit wirst du oft unterschätzt?",
    "Welches Auto ist/war dein Traumauto für dein erstes Eigenes?",
    "An welchem Gegenstand hängst du emotional am Meisten?",
    "Womit fängst du immer wieder an, obwohl du weißt, dasss du es eh nie durchziehen wirst?",
    "Was ist dein 'toxic Trait'?",
    "Wann empfindest du aktuell Selbsthass?",
    "Wie sieht dein perfekter 'Cheatday' aus?",
    "Stichwort 'Auswandern': <br/>Welches Land kommt dir als erstes in den Sinn?",
    "Was würdest du hamstern, wenn es drauf ankommt?",
    "hast du eine Lieblingsballade?",
    "Was ist deiner Meinung nach das beste Brettspiel?",
    "Was an deinem Körper verstehst du nicht?",
    "Welches Auto findest du optisch am Geilsten?",
    "Was machtst du nur, wenn es wirklich sein muss?",
    "Dienstag oder Donnerstag <br/>- Welcher Tag ist irgendwie schlimmer?",
    "Gibt es eine (Haus-)Arbeit, die andere blöd finden, du aber ganz gerne machst?",
    "Worauf freust du dich gerade am Meisten?",
    "Was ist deine go-to Backware?",
    "Was aus deiner Kindheit hast du noch zuhause aufbewahrt, von dem du weißt, <br/>dass du es nie wieder benutzen, es aber auch niemals wegschmeißen wirst?",
    "Über welche Sache die du mal konntest, sie aber jetzt nicht mehr kannst, bist du am Traurigsten?",
    "Welche Sachen, die in Filmen völlig normal sind, sind im echten Leben komplett 'weird'?",
    "Welche Phrasen benutzt du zu oft?",
    "Welchen Emoji benutzt du zurzeit unverhältnismäßig oft?",
    "Welchen Fehler würdest du als Elternteil auf jeden Fall machen?",
    "Hattest du eine Zahnspange?",
    "Hattest du schon einmal ein Loch im Zahn?",
    "Wie viel Money ist 'Fuck-you-money'?",
    "Welches 'Codewort' benutzt du für Gras?",
    "Welche deiner Eigenschaften macht ein Zusammenleben mit dir eher schwierig?",
    "Was hat dir als Kind die meiste Freude bereitet?",
    "Hat sich irgendeine Charaktereigenschaft von dir, die du mal hattest, fundamental verändert?",
    "Welches Produkt hat der Markt so richtig aus deinem Leben weggeregelt?",
    "Was glaubst du, welchen Job du im Mittelalter ausgeübt hättest?",
    "Gibt es Rituale in deiner Familie?",
    "Was ist dein 'Daily-ritual'?",
    "Welche 'Bubble' glaubst du ist die Kleinkriminellste?",
    "Gibt es kleine Dinge im Alltag <br/>- Alles was man nicht kaufen kann - <br/>die dich glücklich machen?",
    "Wann bist du das letzte Mal so richtig 'geinfluenced' worden?",
    "Was ist der klischeemännlichste Rat, den dir dein Vater jemals gegeben hat?",

    /* Season 4 */
    "Welchen modischen Fehltritt deinerseits bereust du heute am meisten?",
    "Wovon hast du zu viel?",
    "Gibt es irgendeine Architektur, die irgendwas mit dir macht?",
    "Welchen Traum hast du, von dem du weißt, dass du ihn dir eh nie erfüllen wirst?",
    "Welcher ist dein Lieblingsgeldschein?",
    "Was war dein aktuell letzter Fehlkauf?",
    "Glaubst du an Gott?",
    "Glaubst du ans Schicksal, bzw. an Karma?",
    "Welches Lied, macht dass du sofort saufen willst?",
    "Welchen Tipp den du anderen Leuten gibst, solltest du selbst mal ein biscchen mehr beherzigen?",
    "Thema Bolzplatz: Was waren früher eure Regeln?",
    "Welche Beleidigung die nicht mehr politisch korrekt ist rutscht dir immer wieder mal raus?",
    "Gibt es eine Automarke/ein Auto, mit dem du irgendwas verbindest?",
    "Hattest du irgendeine falsche Annahme über deinen Charakter, die sich als falsch herausgestellt hat?",
    "Was ist das Romantischste, das du je für jemanden getan hast?",
    "Was ist Romantik für dich?",
    "Bist du romantisch?",
    "Was ist das Asozialste das du je auf einer Hausfeier gemacht hast?",
    "Was ist deine krasseste Feiererfahrung?",
    "Was lässt einen gebildet wirken, obwohl es nichts mit Bildung zu tun hat?",
    "Was ist in offiziellen Mail deine go-to 'Closingline'?",
    "Was war der erste Pornofilm, den du gesehen hast?",
    "Die Biografie deines Lebens: Wie lautet der Titel?",
    "Wer ist der netteste Mensch, den du kennst?",
    "Was denkst du als Erstes, wenn du an deine Kindergartenzeit denkst?",
    "Gibt es Essgewohnheiten von dir, die andere ekelhaft finden?",
    "Was war bisher der schönste Tag deines Lebens?",
    "Könntest du bei einem Auto selbständig die Reifen wechseln?",
    "Hast du Angst vor Terroranschlägen?",
    "Wenn du jetzt per Dekret ein Gesetz in Deutschland erlassen könntest, welches wäre es?",
    "Wie sieht dein klassicher Kulturbeutel aus? Was kommt rein?",
    "In welcher olympischen Sportart würdest du es noch schaffen?",
    "Welchen Beruf würdest du ausüben, wenn Geld keine Rolle spielen würde?",
    "Was ist das größte 'Was wäre wenn' in deinem Leben?",
    "Wenn du ein Video von einer bestimmten Situation aus deinem Leben haben könntest - welche wäre es?",
    "Hast du neben den großen Städten einen Sehnsuchtsort in den USA?",
    "Was wäre dein persönlicher Slogan?",
    "Was glaubst du ist an dir irre?",
    "Was glaubst du bewundern andere insgeheim an dir?",
    "Welche Höflichkeitsform oder -geste ist dir wichtig?",
]

// Create Function to Randomize Content
function new_content() {
    var randomContent = Math.floor(Math.random() * (Content.length));
    document.getElementById("content").innerHTML = Content[randomContent];
    Content.splice(randomContent, 1);
}